### PR TITLE
add btcec/package.json

### PR DESCRIPTION
**Pull request by vyzo**
Package hash is QmRoGBYPVMwxPyyEQuMYXBFbXPN1xRYag4CwSBvRWYrKxR
We will have to pin this somehow, as I am publishing from my laptop.

### CODE REVIEW

**Comment by vyzo** [comment]
I am guess I also need to release and commit the .gx directory.

**Comment by vyzo** [comment]
After running `gx release`, package btcec published with hash: Qmct7apXgRK66hqvdokDLtPuZWp2zWPtQ4P2gJjdbtsSS3

**Comment by whyrusleeping** [comment]
Only one small nitpick which isnt really an issue, in pubkey_test.go, an external package is imported. This won't affect gx imports, but its always good to make sure we're aware of that.

**Comment by vyzo** [comment]
Oops, didn't check all the test file imports.
Perhaps we should add a gxignore?

**Comment by whyrusleeping** [comment]
Yeah, we could do that. No need to add test code to the published package.

**Comment by vyzo** [comment]
Should I manually bump the package version for the gxignore?
The hash will change.

**Comment by Kubuxu** [comment]
Yeah, hash changing isn't big problem. You can bump it with `gx version path`.

**Comment by vyzo** [comment]
`gx release minor` actually bumped it:
```
$ gx release patch
updated version to: 0.0.1
package btcec published with hash: QmWq5PJgAQKDWQerAijYUVKW8mN5MDatK5j7VMp8rizKQd
[gx-vendor-btcec 3c106f0] gx publish 0.0.1
```

**Comment by vyzo** [comment]
We have pinned in an AWS node for now, so the packages should be reasonably available.

**Comment by whyrusleeping** [comment]
@vyzo cool, make sure to add the .gx/lastpubver to git and push it up here

**Comment by vyzo** [comment]
Yup, it's commited and pushed.

**Pull request merged**
